### PR TITLE
Add TelegramBotSend task

### PR DESCRIPTION
**Pull request by moadibfr**
I removed dependency on external lib to send message to the Telegram bot API because I only really needed to be able to send message.

I made a really naive sendMessage that use URL.openConnection. I thought it could be nice to inject a micronaut httpclient but could not make that work in an acceptable time. Also I did not find a solution to prevent the Kestra documentation showing the internal client when I did that.

This use [Telegram Bot API](https://core.telegram.org/bots/api), please use [telegram documentation](https://core.telegram.org/bots) to create a bot and get a token.

### CODE REVIEW

**Comment by tchiotludo** [comment]
hey @moadibfr, thanks for this one.
 
The micronaut example can be found [here](https://github.com/kestra-io/plugin-powerbi/blob/020b38787004afbcf986ca1aff5f8dced7a27cb8/src/main/java/io/kestra/plugin/powerbi/AbstractPowerBi.java), it's our way to handle micronaut http client. 
Can you make on that way please to have a consistent way to handle simple http plugin? 

The best will be to support the same than other notification systems [here](https://github.com/kestra-io/plugin-notifications/tree/master/src/main/java/io/kestra/plugin/notifications/slack): to enable custom message but also support notification about kestra execution, tell me if you have the time to support it or not :sweat_smile:

**Comment by moadibfr** [comment]
> hey @moadibfr, thanks for this one.
> 
> The micronaut example can be found [here](https://github.com/kestra-io/plugin-powerbi/blob/020b38787004afbcf986ca1aff5f8dced7a27cb8/src/main/java/io/kestra/plugin/powerbi/AbstractPowerBi.java), it's our way to handle micronaut http client. Can you make on that way please to have a consistent way to handle simple http plugin?
> 
> The best will be to support the same than other notification systems [here](https://github.com/kestra-io/plugin-notifications/tree/master/src/main/java/io/kestra/plugin/notifications/slack): to enable custom message but also support notification about kestra execution, tell me if you have the time to support it or not 😅

Nice I'll try to rework using the micronaut example then I digged into some plugin but not this one... 
I saw the notification plugin but I though it might not be a good idea to duplicate how we get execution information and I really initially just wanted to play with the kestra plugin ;)
But I don't think it would be so much time to update with the same set of functionalities so I'll try to work on that next week 👍

**Comment by moadibfr** [comment]
hey @tchiotludo I tried to implement the same feature as the slack notification plugin however telegram message formatting is not the best (I tried with markdown but it does not give that much formatting option and it requires strange char escaping for the messages...).
Also I just copied the full service and the interface I'm not sure there is something better to do apart from just importing this one in the notification plugin.

**Comment by loicmathieu** [comment]
@moadibfr if it didn't use any other libraries that the one already present in the plugin-notification I think the best would be to add those tasks in the existing plugin to avoid the plugin JAR overhead.
If it's OK for you, would you open a PR on it ?

**Comment by tchiotludo** [comment]
deleting this repository since the telegram plugin will on notification repository !

**Pull request closed without merging**
